/*
 * myapi
 *
 * HTTP server in GO with swagger codegen
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	sw "swagger-codegen-example2/basic_auth_server/go"
    //dbapi "myapi/server/controller"
    //server "myapi/server"
)

func main() {
	log.Printf("Server started")

    //defer dbapi.DbClose()
    //dbapi.DbInit()

    //server.InnerHandlerMap["AddPet"] = server.AddMyPet
    //server.InnerHandlerMap["DeletePet"] =  server.DeleteMyPet
    //server.InnerHandlerMap["GetPetById"] =  server.GetMyPetById
    //server.InnerHandlerMap["FindPetsByTags"] =  server.FindMyPetsByTags

	router := sw.NewRouter()
	log.Fatal(http.ListenAndServe(":8080", router))
}
